repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
        - --configfile
        - bandit.yaml
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
        - --line-length
        - "120"
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: 
        - --profile
        - black
        - --known-local-folder
        - wordlesolver
        - --known-local-folder
        - tests
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.990"
    hooks:
      - id: mypy
        args:
        - --follow-imports=silent
        - --ignore-missing-imports
        - --show-column-numbers
        - --no-pretty
        - --strict
        additional_dependencies:
        - gym==0.26.2
        - pytest==7.2.0
        - types-requests==2.28.11.4
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint
        additional_dependencies:
        - gym==0.21.0
        - pytest-playwright==0.3.0
        - tqdm==4.64.1
