name: wordlesolver
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - poetry=1.1.15
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pytorch-cuda=11.7
  - stable-baselines3=1.1.0
