name: wordlesolver
channels:
  - conda-forge
dependencies:
  - bandit=1.7.4
  - black=22.6.0
  - gym=0.21.0
  - isort=5.10.1
  - mypy=0.990
  - pip=22.2.2
  - pre-commit=2.20.0
  - pydocstyle=6.1.1
  - pylint=2.15.3
  - pytest=7.2.0
  - python=3.10
  - tqdm=4.64.1
  - types-requests=2.28.11.4
  - pip:
    - pytest-playwright==0.3.0
