name: wordlesolver
channels:
  - conda-forge
dependencies:
  - black=22.6.0
  - isort=5.10.1
  - pip=22.2.2
  - pre-commit=2.20.0
  - pylint=2.15.3
  - pytest=7.2.0
  - python=3.10
  - tqdm=4.64.1
  - pip:
    - pytest-playwright==0.3.0
