version: '3'

tasks:
  build:
    desc: Builds and installs project with dependencies and pre-commit
    cmds:
      - conda env create -f environment.yml
      - conda run -n wordlesolver poetry install
      - conda run -n wordlesolver playwright install
      - conda run -n wordlesolver pre-commit install --hook-type commit-msg
    interactive: true

  run:
    desc: Runs specified solver with specified generator
    cmds:
      - conda run --live-stream -n wordlesolver python main.py {{.CLI_ARGS}}

  train:
    desc: Trains specified solver
    cmds:
      - conda run --live-stream -n wordlesolver python train.py {{.CLI_ARGS}}

  test:
    cmds:
      - conda run --live-stream -n wordlesolver pytest tests/

  lint:
    cmds:
      - conda run --live-stream -n wordlesolver pre-commit run --all-files
