name: CI

on: [pull_request, push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: arduino/setup-task@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: snok/install-poetry@v1
    - name: Run pre-commit
      shell: bash -l {0}
      run: task build lint
  tests:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1
      - name: Run tests
        shell: bash -l {0}
        run: task build test
